name: Library Build CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
        with:
          build-args: "Signaculum"
